import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Sprint 4 - Porto',
  description: 'Generated by Complex',
}

export default function RootLayout({ children }) {
  return (
    <html lang="pt-br">
      <body className={inter.className}>{children}</body>
      <Cabecalho/>
          {children}
        <Rodape/>
    </html>
  )
}
